server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useSSL=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: ZHANGYAWEIsw8812

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl